export const acaoCorretora = {
   LISTA: "LISTAR_CORRETORA",
   EXCLUI : 'EXCLUIR_CORRETORA',
   ALTERA : 'ALTERAR_CORRETORA',  
   ADICIONA : 'ADICIONAR_CORRETORA'
};

export const acaoTipoInvestimnento = {
   LISTA: "LISTAR_TIPOINVESTIMENTO",
   EXCLUI : 'EXCLUIR_TIPOINVESTIMENTO',
   ALTERA : 'ALTERAR_TIPOINVESTIMENTO',  
   ADICIONA : 'ADICIONAR_TIPOINVESTIMENTO'
};

export const acaoPapel = {
   LISTA: "LISTAR_PAPEL",
   EXCLUI : 'EXCLUIR_PAPEL',
   ALTERA : 'ALTERAR_PAPEL',  
   ADICIONA : 'ADICIONAR_PAPEL'
};
